### Healthcheck
GET http://localhost:3002/health

##################################################

### Agendar consulta
POST http://localhost:3000/consulta
Content-Type: application/json
Authorization: Bearer ???

{
    "agendaId": "6a9d3e75-06e2-4066-aa4a-9c2a5f44ba3f"
}
