kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume # Sets PV's name
  namespace: health-med
  labels:
    type: local # Sets PV's type to local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim # Sets name of PVC
  namespace: health-med
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany # Sets read and write access
  resources:
    requests:
      storage: 1Gi # Sets volume size
