apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: health-med
type: Opaque
data:
  # Dica: Você pode usar o https://www.base64encode.org/ para converter de/para Base64
  POSTGRES_USER: cGd1c2Vy
  POSTGRES_PASSWORD: cGdwd2Q=
  
# ATENÇÃO: Evite fazer commit dos Secrets do Kubernetes em repositórios públicos
# Para mais informações visite https://kubernetes.io/docs/concepts/security/secrets-good-practices/#avoid-sharing-secret-manifests
